# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage:
name: 
# Get AWS creds from Hashicorp Vault 

# Setup CDK environment by building AWS CLI and CDK 

# Deploy using established environment and credentials 

# Extract targets from the build outputs of the CDK build 

# Download source from other github repo and deploy static website code to
# bucket target